In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Members.csv")

# View first rows
df.head()

,title,login,first_name,last_name,create_time,count
0,,mjohn,John,M,08-01-2025 16:37,12
1,,dmarie,Marie,D,08-01-2025 16:35,7
2,Ms,cmarie,Marie,C,08-01-2025 16:37,21
3,Ms,smonika,Monika,S,08-01-2025 16:36,57
4,Mr,fjohn,John,F,08-01-2025 16:35,4


In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        13 non-null     str  
 1   login        13 non-null     str  
 2   first_name   13 non-null     str  
 3   last_name    13 non-null     str  
 4   create_time  13 non-null     str  
 5   count        13 non-null     int64
dtypes: int64(1), str(5)
memory usage: 1.1 KB


title          0
login          0
first_name     0
last_name      0
create_time    0
count          0
dtype: int64

In [5]:
cat_cols = df.select_dtypes(include=['object', 'string']).columns

for col in cat_cols:
    if df[col].notna().any():
        df[col] = df[col].fillna(df[col].mode(dropna=True)[0])

In [6]:
df = pd.get_dummies(df, drop_first=True)

In [8]:
print(df.head())

   count  title_ Mr  ...  create_time_12-11-2024 14:46  create_time_13-10-2024 14:23
0     12      False  ...                         False                         False
1      7      False  ...                         False                         False
2     21      False  ...                         False                         False
3     57      False  ...                         False                         False
4      4       True  ...                         False                         False

[5 rows x 43 columns]


In [11]:
print(df.columns)

Index(['count', 'title_ Mr', 'title_ Ms', 'login_dmarie', 'login_fjohn',
       'login_gbill', 'login_jsteve', 'login_lstephie', 'login_melon',
       'login_mjohn', 'login_plarry', 'login_praj', 'login_sbrin',
       'login_smonika', 'login_stony', 'first_name_Brin', 'first_name_Elon',
       'first_name_John', 'first_name_Larry', 'first_name_Marie',
       'first_name_Monika', 'first_name_Raj', 'first_name_Stephie',
       'first_name_Steve', 'first_name_Tony', 'last_name_D', 'last_name_F',
       'last_name_G', 'last_name_J', 'last_name_L', 'last_name_M',
       'last_name_P', 'last_name_S', 'create_time_06-01-2025 07:05',
       'create_time_07-01-2025 16:21', 'create_time_08-01-2025 16:01',
       'create_time_08-01-2025 16:31', 'create_time_08-01-2025 16:35',
       'create_time_08-01-2025 16:36', 'create_time_08-01-2025 16:37',
       'create_time_11-09-2021 14:35', 'create_time_12-11-2024 14:46',
       'create_time_13-10-2024 14:23'],
      dtype='str')


In [14]:
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

In [19]:
print(df.shape)
print(df.columns)

(13, 43)
Index(['count', 'title_ Mr', 'title_ Ms', 'login_dmarie', 'login_fjohn',
       'login_gbill', 'login_jsteve', 'login_lstephie', 'login_melon',
       'login_mjohn', 'login_plarry', 'login_praj', 'login_sbrin',
       'login_smonika', 'login_stony', 'first_name_Brin', 'first_name_Elon',
       'first_name_John', 'first_name_Larry', 'first_name_Marie',
       'first_name_Monika', 'first_name_Raj', 'first_name_Stephie',
       'first_name_Steve', 'first_name_Tony', 'last_name_D', 'last_name_F',
       'last_name_G', 'last_name_J', 'last_name_L', 'last_name_M',
       'last_name_P', 'last_name_S', 'create_time_06-01-2025 07:05',
       'create_time_07-01-2025 16:21', 'create_time_08-01-2025 16:01',
       'create_time_08-01-2025 16:31', 'create_time_08-01-2025 16:35',
       'create_time_08-01-2025 16:36', 'create_time_08-01-2025 16:37',
       'create_time_11-09-2021 14:35', 'create_time_12-11-2024 14:46',
       'create_time_13-10-2024 14:23'],
      dtype='str')


In [25]:
df.head()
df.columns

Index(['count', 'title_ Mr', 'title_ Ms', 'login_dmarie', 'login_fjohn',
       'login_gbill', 'login_jsteve', 'login_lstephie', 'login_melon',
       'login_mjohn', 'login_plarry', 'login_praj', 'login_sbrin',
       'login_smonika', 'login_stony', 'first_name_Brin', 'first_name_Elon',
       'first_name_John', 'first_name_Larry', 'first_name_Marie',
       'first_name_Monika', 'first_name_Raj', 'first_name_Stephie',
       'first_name_Steve', 'first_name_Tony', 'last_name_D', 'last_name_F',
       'last_name_G', 'last_name_J', 'last_name_L', 'last_name_M',
       'last_name_P', 'last_name_S', 'create_time_06-01-2025 07:05',
       'create_time_07-01-2025 16:21', 'create_time_08-01-2025 16:01',
       'create_time_08-01-2025 16:31', 'create_time_08-01-2025 16:35',
       'create_time_08-01-2025 16:36', 'create_time_08-01-2025 16:37',
       'create_time_11-09-2021 14:35', 'create_time_12-11-2024 14:46',
       'create_time_13-10-2024 14:23'],
      dtype='str')

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# train model
et = ExtraTreesClassifier(random_state=42)
et.fit(X_train, y_train)

# predictions
et_pred = et.predict(X_test)

# evaluation
print("Extra Trees Accuracy:", accuracy_score(y_test, et_pred))
print("\nClassification Report:\n", classification_report(y_test, et_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, et_pred))

Extra Trees Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [29]:
print(hasattr(rf_model, "estimators_"))

False
